name: 'Build and publish Linux applications'
on:
  create:
    branches:
      - release/**
  push:
    branches:
    - master
    - dev/**
    paths:
    - TimetableApp/TimetableApp.Skia.Gtk/**
    - TimetableApp/TimetableApp.Shared/**
    - .github/workflows/**
  pull_request:
    branches:
    - master
    paths:
    - TimetableApp/TimetableApp.Skia.Gtk/**
    - TimetableApp/TimetableApp.Shared/**
    - .github/workflows/**

jobs:
  build:
    name: Build app (GTK)
    runs-on: ubuntu-latest
    steps:
        # Checkout the code
        - uses: actions/checkout@v2

        # Install .NET Core SDK
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 5.0.x

        # .NET core, framework dependent binaries.
        - name: Publish
          run: dotnet publish TimetableApp/TimetableApp.Skia.Gtk/TimetableApp.Skia.Gtk.csproj --configuration Release

        - name: Publish package
          uses: actions/upload-artifact@v2
          with:
            name: TimetableApp.Skia.Gtk
            path: TimetableApp/TimetableApp.Skia.Gtk/bin/Release/net5.0/publish/**

        # .NET on Linux does not support x86: https://github.com/dotnet/runtime/issues/31180
        # - name: Publish standalone (x86)
        #   run: dotnet publish TimetableApp/TimetableApp.Skia.Gtk/TimetableApp.Skia.Gtk.csproj --configuration Release -p:PublishSingleFile=true -r linux-x86 --self-contained false

        # - name: Publish standalone package (x86)
        #   uses: actions/upload-artifact@v2
        #   with:
        #     name: TimetableApp.Skia.Gtk.Standalone.x86
        #     path: TimetableApp/TimetableApp.Skia.Gtk/bin/Release/net5.0/linux-x86/publish/TimetableApp.Skia.Gtk.exe

        - name: Publish standalone (x64)
          run: dotnet publish TimetableApp/TimetableApp.Skia.Gtk/TimetableApp.Skia.Gtk.csproj --configuration Release -p:PublishSingleFile=true -r linux-x64 --self-contained false

        - name: Publish standalone package (x64)
          uses: actions/upload-artifact@v2
          with:
            name: TimetableApp.Skia.Gtk.Standalone.x64
            path: TimetableApp/TimetableApp.Skia.Gtk/bin/Release/net5.0/linux-x64/publish/**

        # - name: Publish self-contained (x86)
        #   run: dotnet publish TimetableApp/TimetableApp.Skia.Gtk/TimetableApp.Skia.Gtk.csproj --configuration Release -p:PublishSingleFile=true -r linux-x86

        # - name: Publish self-contained package (x86)
        #   uses: actions/upload-artifact@v2
        #   with:
        #     name: TimetableApp.Skia.Gtk.SelfContained.x86
        #     path: TimetableApp/TimetableApp.Skia.Gtk/bin/Release/net5.0/linux-x86/publish/TimetableApp.Skia.Gtk.exe

        - name: Publish self-contained (x64)
          run: dotnet publish TimetableApp/TimetableApp.Skia.Gtk/TimetableApp.Skia.Gtk.csproj --configuration Release -p:PublishSingleFile=true -r linux-x64

        - name: Publish self-contained package (x64)
          uses: actions/upload-artifact@v2
          with:
            name: TimetableApp.Skia.Gtk.SelfContained.x64
            path: TimetableApp/TimetableApp.Skia.Gtk/bin/Release/net5.0/linux-x64/publish/**

        # To-Do: Publish snap?